training:
  lr: 0.01
  weight-decay: 0.0000001
  bs: 4  # Further reduced batch size from 8 to 4
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 15
  rebalancing-fake: 0.3
  rebalancing-real: 1
  frames-per-video: 30  # Equidistant frames

model:
  image-size: 380  # Ensure this is divisible by both patch sizes
  num-classes: 1
  depth: 6  # Increase the number of multi-scale encoding blocks
  sm-dim: 384  # Adjust dimensions for higher capacity
  sm-patch-size: 10  # Ensure this divides the image size without remainder
  sm-enc-depth: 4  # Increase depth
  sm-enc-dim-head: 64
  sm-enc-heads: 8
  sm-enc-mlp-dim: 2048
  lg-dim: 768  # Adjust dimensions for higher capacity
  lg-patch-size: 20  # Ensure this divides the image size without remainder
  lg-enc-depth: 4
  lg-enc-dim-head: 64
  lg-enc-heads: 8
  lg-enc-mlp-dim: 2048
  cross-attn-depth: 4  # Increase cross attention rounds
  cross-attn-dim-head: 64
  cross-attn-heads: 8
  lg-channels: 56  # Adjust channels based on EfficientNet-B7
  sm-channels: 2560  # Adjust channels based on EfficientNet-B7
  dropout: 0.3
  emb-dropout: 0.3
